env: "local"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 30s
  user: "misha"
  #  password: "mypass"
storage:
  host: "host"
  port: 5432
  sslmode: "disable"



