env: "local"

http_server:
  address: "backend:8080"
  timeout: 4s
  idle_timeout: 30s
#  user: "misha"
  #  password: "mypass"
storage:
  host: "db"
  port: 5432
  sslmode: "disable"



