version: '3.8'
services:
  backend:
    container_name: backend
    hostname: backend
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      default:
        ipv4_address: 192.168.65.3
  pinger:
    container_name: pinger
    hostname: pinger
    build: ./pinger
    links:
      - backend
    restart: always
    networks:
      default:
        ipv4_address: 192.168.65.4
  db:
    container_name: db
    hostname: db
    build: ./database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      default:
        ipv4_address: 192.168.65.5
  frontend:
    container_name: frontend
    hostname: frontend
    build: ./front/ip-address-tracker
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.65.6
networks:
  default:
    driver: bridge
    ipam:
       config:
        - subnet: 192.168.65.0/24