services:
  backend:
    container_name: backend
    hostname: backend
    env_file:
      - ./backend/.env
    build: ./backend
    ports:
      - "8081:8081"
#    restart: always
    networks:
      ip_address_pinger:
        ipv4_address: 172.16.0.3
  pinger:
    container_name: pinger
    hostname: pinger
    build: ./pinger
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - backend
    restart: always
    networks:
      ip_address_pinger:
        ipv4_address: 172.16.0.4
  db:
    container_name: db
    hostname: db
    build: ./database
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      ip_address_pinger:
        ipv4_address: 172.16.0.5
  frontend:
    build: ./front/ip-address-tracker
    container_name: frontend
    hostname: frontend
    ports:
      - "80:80"
    networks:
      ip_address_pinger:
        ipv4_address: 172.16.0.6
networks:
  ip_address_pinger:
    driver: bridge
    ipam:
       config:
        - subnet: 172.16.0.0/16